version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(frontend):"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(backend):"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(frontend docker):"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(backend docker):"
